### PR TITLE
Ojs3.2.1, Bootstrap3 theme. Issue with Full Issues.

### PR DESCRIPTION
**Pull request by sioulasdimitris**
Plugin works when I want to view an article. When I want to view a full issue it doesn't work.

### CODE REVIEW

**Comment by asmecher** [comment]
Thanks, @sioulasdimitris! But could you describe the problem, and your solution, in more detail?

**Comment by sioulasdimitris** [comment]
The Hypothesis plugin used to work only when I wanted to view an article by checking the name of the file. 
$tpl = 'submissionGalley.tpl';
if (strpos($template, $plugin) !== false && strpos($template, ':'.$tpl,  -1 - strlen($tpl)) !== false) {	
After the new edit works also same way when I want to view a full issue by adding the full issue file's name to the code.
$submissiontpl = 'submissionGalley.tpl';
$issuetpl = 'issueGalley.tpl';
if ( (strpos($template, $plugin) !== false) && (  (strpos($template, ':'.$submissiontpl,  -1 - strlen($submissiontpl)) !== false)  ||  (strpos($template, ':'.$issuetpl,  -1 - strlen($issuetpl)) !== false)))

**Comment by asmecher** [comment]
Thanks, @sioulasdimitris -- merged!

**Comment by sioulasdimitris** [comment]
Hello @asmecher, thank you again. 

Please keep in mind that we want to make another pull request in order to add extra features to hypothesis plugin like supporting epub files. 

But first we need an epub viewer plugin for Ojs in order to view epub files.
So we created an epubJsViewer plugin and we made a pull request https://github.com/pkp/plugin-gallery/pull/12.

WE would appreciate if you could review and accept our pull request for epubJsViewer plugin so we can proceed. 

Thank you in advance,
Dimitris

**Pull request merged**
